
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: polygonus_marketplace
      MYSQL_USER: polygonus
      MYSQL_PASSWORD: root
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

    ports:
      - "3307:3306"